const db = require('../db')
const { Player, Position } = require('../models')


db.on('error', console.error.bind(console, 'MongoDb connection erorr:'))

const main = async () => {
    const center = await new Position({
        name: "Center",
        description: "The center is the tallest player on each team, playing near the basket. On offense, the center tries to score on close shots and rebound. But on defense, the center tries to block opponents’ shots and rebound their misses.",
    })
    center.save()
    
    const forward = await new Position({
        name: "Forward",
        description: "There are two types of forward. The power forward does many of the things a center does, playing near the basket while rebounding and defending taller players. But power forwards also take longer shots than centers. The small forward plays against small and large players. They roam all over on the court. Small forwards can score from long shots and close ones.",
    })
    forward.save()
    
    const guard = await new Position({
        name: "Guard",
        description: "There are also two types of guard. The point guard runs the offense and usually is the team’s best dribbler and passer. The point guard defends the opponent’s point guard and tries to steal the ball. The shooting guard is usually the team’s best shooter. The shooting guard can make shots from long distance and also is a good dribbler.",
    })
    guard.save()




    const players = [
        {
            name: "Kareem Abdul-Jabbar",
            position: center._id,
            points: "38,387",
            rebounds: "17,440",
            assists: "5,660",
            championships: "6 times (1971, 1980, 1982, 1985, 1987, 1988)",
            HoFYear: "1995",
            bioHighlight: "GAME-CHANGING IMPACT ON AND OFF COURT.",
            biography: "Kareem Abdul-Jabbar is perhaps the most accomplished player in NBA history, collecting Rookie of the Year honors, six NBA MVPs, two Finals MVPs and six NBA titles. He was one of the most consistent players in league history and still stands as the game's all-time leading scorer.",
            image: "https://cdn.nba.com/manage/2021/10/kareem_abdul_Jabbar6-scaled.jpg",
            video: "",
        },
        {
            name: "Michael Jordan",
            position: guard._id,
            points: "32,292",
            rebounds: "6,672",
            assists: "5,633",
            championships: " 6 times (1991, 1992, 1993, 1996, 1997, 1998)",
            HoFYear: "2009",
            bioHighlight: "A LEGACY OF CULTURAL GAME-CHANGING.",
            biography: "Arguably the greatest player in NBA history, and widely acclaimed as the most potent scorer with 10 scoring titles, Michael Jordan boasts a lifetime average of 30.1 and a 33.5 average in the postseason (all NBA records).",
            image: "https://cdn.nba.com/manage/2021/10/michaeljordan_2-scaled.jpg",
            video: "",
        },
        {
            name: "Bill Russell",
            position: center._id,
            points: "14,522",
            rebounds: "21,620",
            assists: "4,100",
            championships: "11 times (1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1968, 1969)",
            HoFYear: "1975",
            bioHighlight: "A LASTING LEGACY THAT BROKE BARRIERS.",
            biography: "With 11 championships to his name, Bill Russell is cemented as arguably the greatest winner in NBA history. The five-time MVP averaged 15.1 points and 22.5 rebounds per game (second all-time) in his 13-year career and with him at the helm, the Celtics were a dynasty in the late 1950s and early '60s, winning 11 championships and making 12 NBA Finals in 13 seasons.",
            image: "https://cdn.nba.com/manage/2021/10/bill_russell6-scaled.jpg",
            video: "",
        },
        {
            name: "Lebron James",
            position: forward._id,
            points: "37,024",
            rebounds: "10,203",
            assists: "10,041",
            championships: "4 times (2012, 2013, 2016, 2020)",
            HoFYear: "TBD",
            bioHighlight: "RARE COMBINATION OF SIZE, SKILL AND SAVVY.",
            biography: "A contender for the moniker of best NBA player of all time, LeBron James appears to be the rare case of a player seemingly performing in his prime over the course of nearly 20 years. A four-time MVP, four-time NBA champion and four-time Finals MVP, James turns 37 in December, but has averaged at least 25 points in every season except his rookie year (2003-04), in which he won Rookie of the Year.",
            image: "https://cdn.nba.com/manage/2021/10/lebronjames_9-scaled.jpg",
            video: "",
        },
        {
            name: "Wilt Chamberlain",
            position: center._id,
            points: "31,419",
            rebounds: "23,924",
            assists: "4,643",
            championships: "2 times (1967, 1972)",
            HoFYear: "1979",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Magic Johnson",
            position: guard._id,
            points: "17,707",
            rebounds: "6,559",
            assists: "10,141",
            championships: "5 times (1980, 1982, 1985, 1987, 1988)",
            HoFYear: "2002",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Larry Bird",
            position: forward._id,
            points: "21,791",
            rebounds: "8,974",
            assists: "5,695",
            championships: "3 times (1981, 1984, 1986)",
            HoFYear: "1998",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Moses Malone",
            position: center._id,
            points: "27,409",
            rebounds: "16,212",
            assists: "1,796",
            championships: "1 time (1983)",
            HoFYear: "2001",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Giannis Antetokounmpo",
            position: forward._id,
            points: "12,319",
            rebounds: "5,371",
            assists: "2,632",
            championships: "1 time (2021)",
            HoFYear: "TBD",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Stephen Curry",
            position: guard._id,
            points: "18,434",
            rebounds: "3,503",
            assists: "4,984",
            championships: "3 times (2015, 2017, 2018)",
            HoFYear: "TBD",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Steve Nash",
            position: guard._id,
            points: "17,387",
            rebounds: "3,642",
            assists: "10,335",
            championships: "None",
            HoFYear: "2018",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Tim Duncan",
            position: forward._id,
            points: "26,496",
            rebounds: "15,091",
            assists: "4,225",
            championships: "5 times (1999, 2003, 2005, 2007, 2014)",
            HoFYear: "2020",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Karl Malone",
            position: forward._id,
            points: "36,928",
            rebounds: "14,968",
            assists: "5,248",
            championships: "None",
            HoFYear: "2010",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Bob Pettit",
            position: forward._id,
            points: "20,880",
            rebounds: "12,849",
            assists: "2,369",
            championships: "1 time (1958)",
            HoFYear: "1971",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "James Harden",
            position: guard._id,
            points: "22,045",
            rebounds: "4,794",
            assists: "5,730",
            championships: "None",
            HoFYear: "TBD",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Russell Westbrook",
            position: guard._id,
            points: "21,857",
            rebounds: "6,961",
            assists: "8,061",
            championships: "None",
            HoFYear: "TBD",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Kevin Durant",
            position: forward._id,
            points: "23,883	",
            rebounds: "6,239",
            assists: "3,681",
            championships: "2 times (2017, 2018)",
            HoFYear: "TBD",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Kobe Bryant",
            position: guard._id,
            points: "33,643",
            rebounds: "7,047",
            assists: "6,306",
            championships: "5 times (2000, 2001, 2002, 2009, 2010)",
            HoFYear: "2020",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Dirk Nowitzki",
            position: forward._id,
            points: "31,560",
            rebounds: "11,489",
            assists: "3,651",
            championships: "1 time (2011)",
            HoFYear: "TBD",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Kevin Garnett",
            position: forward._id,
            points: "26,071",
            rebounds: "14,662",
            assists: "5,445",
            championships: "1 time (2008)",
            HoFYear: "2020",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Allen Iverson",
            position: guard._id,
            points: "24,368",
            rebounds: "3,394",
            assists: "5,624",
            championships: "None",
            HoFYear: "2016",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Shaquille O'Neal",
            position: center._id,
            points: "28,596",
            rebounds: "13,099",
            assists: "3,026",
            championships: "4 times (2000, 2001, 2002, 2006)",
            HoFYear: "2016",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "David Robinson",
            position: center._id,
            points: "20,790",
            rebounds: "10,497",
            assists: "2,441",
            championships: "2 times (1999, 2003)",
            HoFYear: "2009",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Hakeem Olajuwon",
            position: center._id,
            points: "26,946",
            rebounds: "13,748",
            assists: "3,058",
            championships: "2 times (1994, 1995)",
            HoFYear: "2008",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },
        {
            name: "Charles Barkley",
            position: forward._id,
            points: "23,757",
            rebounds: "12,546",
            assists: "4,215",
            championships: "None",
            HoFYear: "2006",
            bioHighlight: "",
            biography: "",
            image: "",
            video: "",
        },

    ]


    await Player.insertMany(players)
    console.log('Players create')
}

const run = async () => {
    await main()
    db.close()
}

run()




// {
//     name: "",
//     position: "",
//     points: "",
//     rebounds: "",
//     assists: "",
//     championships: "",
//     HoFYear: "",
//     bioHighlight: "",
//     biography: "",
//     image: "",
//     video: "",
// },




//Postion description credit:
//https://jr.nba.com/basketball-positions/

//Players stats, bio highlights/biography:
//https://www.nba.com/75/team