const db = require('../db')
const { Player, Position } = require('../models')


db.on('error', console.error.bind(console, 'MongoDb connection erorr:'))

const main = async () => {
    const center = await new Position({
        name: "Center",
        description: "The center is the tallest player on each team, playing near the basket. On offense, the center tries to score on close shots and rebound. But on defense, the center tries to block opponents’ shots and rebound their misses.",
    })
    center.save()
    
    const forward = await new Position({
        name: "Forward",
        description: "There are two types of forward. The power forward does many of the things a center does, playing near the basket while rebounding and defending taller players. But power forwards also take longer shots than centers. The small forward plays against small and large players. They roam all over on the court. Small forwards can score from long shots and close ones.",
    })
    forward.save()
    
    const guard = await new Position({
        name: "Guard",
        description: "There are also two types of guard. The point guard runs the offense and usually is the team’s best dribbler and passer. The point guard defends the opponent’s point guard and tries to steal the ball. The shooting guard is usually the team’s best shooter. The shooting guard can make shots from long distance and also is a good dribbler.",
    })
    guard.save()




    const players = [
        {
            name: "Kareem Abdul-Jabbar",
            position: center._id,
            points: "38,387",
            rebounds: "17,440",
            assists: "5,660",
            championships: "6 times (1971, 1980, 1982, 1985, 1987, 1988)",
            HoFYear: "1995",
            bioHighlight: "GAME-CHANGING IMPACT ON AND OFF COURT.",
            biography: "Kareem Abdul-Jabbar is perhaps the most accomplished player in NBA history, collecting Rookie of the Year honors, six NBA MVPs, two Finals MVPs and six NBA titles. He was one of the most consistent players in league history and still stands as the game's all-time leading scorer.",
            image: "https://cdn.nba.com/manage/2021/10/kareem_abdul_Jabbar6-scaled.jpg",
        },
        {
            name: "Michael Jordan",
            position: guard._id,
            points: "32,292",
            rebounds: "6,672",
            assists: "5,633",
            championships: " 6 times (1991, 1992, 1993, 1996, 1997, 1998)",
            HoFYear: "2009",
            bioHighlight: "A LEGACY OF CULTURAL GAME-CHANGING.",
            biography: "Arguably the greatest player in NBA history, and widely acclaimed as the most potent scorer with 10 scoring titles, Michael Jordan boasts a lifetime average of 30.1 and a 33.5 average in the postseason (all NBA records).",
            image: "https://cdn.nba.com/manage/2021/10/michaeljordan_2-scaled.jpg",
        },
        {
            name: "Bill Russell",
            position: center._id,
            points: "14,522",
            rebounds: "21,620",
            assists: "4,100",
            championships: "11 times (1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1968, 1969)",
            HoFYear: "1975",
            bioHighlight: "A LASTING LEGACY THAT BROKE BARRIERS.",
            biography: "With 11 championships to his name, Bill Russell is cemented as arguably the greatest winner in NBA history. The five-time MVP averaged 15.1 points and 22.5 rebounds per game (second all-time) in his 13-year career and with him at the helm, the Celtics were a dynasty in the late 1950s and early '60s, winning 11 championships and making 12 NBA Finals in 13 seasons.",
            image: "https://cdn.nba.com/manage/2021/10/bill_russell6-scaled.jpg",
        },
        {
            name: "Lebron James",
            position: forward._id,
            points: "37,024",
            rebounds: "10,203",
            assists: "10,041",
            championships: "4 times (2012, 2013, 2016, 2020)",
            HoFYear: "TBD",
            bioHighlight: "RARE COMBINATION OF SIZE, SKILL AND SAVVY.",
            biography: "A contender for the moniker of best NBA player of all time, LeBron James appears to be the rare case of a player seemingly performing in his prime over the course of nearly 20 years. A four-time MVP, four-time NBA champion and four-time Finals MVP, James turns 37 in December, but has averaged at least 25 points in every season except his rookie year (2003-04), in which he won Rookie of the Year.",
            image: "https://cdn.nba.com/manage/2021/10/lebronjames_9-scaled.jpg",
        },
        {
            name: "Wilt Chamberlain",
            position: center._id,
            points: "31,419",
            rebounds: "23,924",
            assists: "4,643",
            championships: "2 times (1967, 1972)",
            HoFYear: "1979",
            bioHighlight: "A PHENOMENAL TALENT THAT DID IT ALL.",
            biography: "Wilt Chamberlain, one of the most unstoppable forces the league has ever seen, retired as a four-time MVP, a two-time NBA champion and the first player to ever score 30,000 points.",
            image: "https://cdn.nba.com/manage/2020/10/wilt-chamberlain-100-points2-784x522.jpg",
        },
        {
            name: "Magic Johnson",
            position: guard._id,
            points: "17,707",
            rebounds: "6,559",
            assists: "10,141",
            championships: "5 times (1980, 1982, 1985, 1987, 1988)",
            HoFYear: "2002",
            bioHighlight: "PURE BRILLIANCE REVOLUTIONIZED THE GAME.",
            biography: "The 6-foot-9 point guard made an immediate impact with the Lakers as he ushered the NBA into a new era with his dazzling passing skills and playmaking ability. He averaged 18.0 points, 7.7 rebounds and 7.3 assists per game during his rookie season and was named an All-Star starter. Alongside Kareem Abdul-Jabbar, Johnson and the Lakers finished the regular season with the top seed in the Western Conference.",
            image: "https://cdn.nba.com/manage/2021/10/JohnsonM90DTB900-scaled.jpg",
        },
        {
            name: "Larry Bird",
            position: forward._id,
            points: "21,791",
            rebounds: "8,974",
            assists: "5,695",
            championships: "3 times (1981, 1984, 1986)",
            HoFYear: "1998",
            bioHighlight: "EXPLOSIVE PLAYMAKING AND A DEADLY SHOT.",
            biography: "A skilled scorer, passer, rebounder and clutch performer, Larry Bird is one of the all-time best all-around players in NBA history. A three-time MVP, Bird won a pair of Finals MVPs and led the Boston Celtics to five NBA Finals appearances and three NBA championships. He is the only person in NBA history to win MVP (1984-86; Celtics), Coach of the Year (Pacers; 1998) and Executive of the Year (Pacers; 2012) in a career.",
            image: "https://cdn.nba.com/manage/2021/10/larrybird_8-scaled.jpg",
        },
        {
            name: "Moses Malone",
            position: center._id,
            points: "27,409",
            rebounds: "16,212",
            assists: "1,796",
            championships: "1 time (1983)",
            HoFYear: "2001",
            bioHighlight: "GENIUS IN THE PAINT THAT MADE IT HAPPEN.",
            biography: "One of the most imposing big men in history, Moses Malone is a three-time MVP, a 12-time All-Star, an NBA champion and the 1983 Finals MVP.",
            image: "https://cdn.nba.com/manage/2021/10/MaloneMoses_94NSBB11159-scaled.jpg",
        },
        {
            name: "Giannis Antetokounmpo",
            position: forward._id,
            points: "12,319",
            rebounds: "5,371",
            assists: "2,632",
            championships: "1 time (2021)",
            HoFYear: "TBD",
            bioHighlight: "AN UNWAVERING WILL TO WIN AND GROW.",
            biography: "Giannis Antetokounmpo has gone from Draft-day gem to one of the best overall NBA players of his generation and, perhaps, league history in very short order. Since debuting in the NBA in 2013, he has been named Most Improved Player, Kia MVP (twice), Defensive Player of the Year and Finals MVP all while helping Milwaukee win a title in 2021, its first since 1971.",
            image: "https://cdn.nba.com/manage/2021/10/giannis_antetokounmpo11-scaled.jpg",
        },
        {
            name: "Stephen Curry",
            position: guard._id,
            points: "18,434",
            rebounds: "3,503",
            assists: "4,984",
            championships: "3 times (2015, 2017, 2018)",
            HoFYear: "TBD",
            bioHighlight: "ELITE SHOOTER REIGNING SUPREME.",
            biography: "Physically unimposing but remarkably elusive and efficient, Stephen Curry is widely touted as the best pure shooter in NBA history. Credited with transforming the league, extending the offensive zone out to 30 feet or beyond with his frequency and accuracy on 3-point attempts.",
            image: "https://cdn.nba.com/manage/2021/10/GettyImages-1235702119.jpg",
        },
        {
            name: "Steve Nash",
            position: guard._id,
            points: "17,387",
            rebounds: "3,642",
            assists: "10,335",
            championships: "None",
            HoFYear: "2018",
            bioHighlight: "REMARKABLY EFFICIENT OFFENSIVE POWER",
            biography: "Steve Nash is considered one of the best passers to ever grace the game after earning five single-season assist crowns and ranking fourth all-time on the NBA career assists list. His playmaking served as a historic engine and the Hall of Fame point guard's teams ranked No.1 in the league in offensive rating in eight out of nine seasons (2002-07, 2009-10).",
            image: "https://cdn.nba.com/manage/2021/10/GettyImages-57558953-scaled.jpg",
        },
        {
            name: "Tim Duncan",
            position: forward._id,
            points: "26,496",
            rebounds: "15,091",
            assists: "4,225",
            championships: "5 times (1999, 2003, 2005, 2007, 2014)",
            HoFYear: "2020",
            bioHighlight: "IMPECCABLE DEFENSE AND ABILITY TO ADAPT.",
            biography: `"The Big Fundamental" is widely regarded as arguably the greatest power forward in NBA history, a dominant defensive anchor and low-post scorer who led the Spurs to five championships over 19 seasons while amassing several individual honors.`,
            image: "https://cdn.nba.com/manage/2021/10/tonyparker_7-scaled.jpg",
        },
        {
            name: "Karl Malone",
            position: forward._id,
            points: "36,928",
            rebounds: "14,968",
            assists: "5,248",
            championships: "None",
            HoFYear: "2010",
            bioHighlight: "A PROLIFIC SCORER THAT ALWAYS DELIVERED.",
            biography: "A bruising, powerful low-post scorer, Karl Malone finished his career with 36,928 points — second only in NBA history to Kareem Abdul-Jabbar. He was a two-time MVP, a 14-time All-NBA performer and played in 82 games in 10 of his 19 NBA seasons.",
            image: "https://cdn.nba.com/manage/2021/10/karl_malone2-scaled.jpg",
        },
        {
            name: "Bob Pettit",
            position: forward._id,
            points: "20,880",
            rebounds: "12,849",
            assists: "2,369",
            championships: "1 time (1958)",
            HoFYear: "1971",
            bioHighlight: "A RELENTLESS ATHLETE ON AND OFF COURT.",
            biography: "Bob Pettit was one of the NBA's first truly great scorers, playing 11 seasons and amassing 20,000 points — the first player in NBA history to reach that mark. He never finished lower than seventh in the NBA scoring race in each of his seasons. The best forward of his era that spanned the 1950s and early '60s, Pettit was an All-Star every season, an All-NBA First Team pick 10 times and made an All-NBA Second Team.",
            image: "https://cdn.nba.com/manage/2021/10/bob_pettit4-scaled.jpg",
        },
        {
            name: "James Harden",
            position: guard._id,
            points: "22,045",
            rebounds: "4,794",
            assists: "5,730",
            championships: "None",
            HoFYear: "TBD",
            bioHighlight: "UNCANNY SKILL AND CONTROL OF THE GAME.",
            biography: "From a super sub to a superstar, James Harden's career journey in the NBA has been marked by success -- particularly as a go-to scorer. By his fourth NBA season, Harden was averaging 25 ppg or more and has collected three scoring crowns, a Kia MVP and been a part of several long playoff runs.",
            image: "https://cdn.nba.com/manage/2021/10/james_harden12-scaled.jpg",
        },
        {
            name: "Russell Westbrook",
            position: guard._id,
            points: "21,857",
            rebounds: "6,961",
            assists: "8,061",
            championships: "None",
            HoFYear: "TBD",
            bioHighlight: "SHOWSTOPPING GAME AND FASHION.",
            biography: "Russell Westbrook is one of the most dynamic players the league has ever seen. The 6-foot-3 point guard is no stranger to the NBA’s record books, largely due to his combination of scoring, playmaking and ability to attack the glass.",
            image: "https://cdn.nba.com/manage/2021/10/GettyImages-463541414-scaled.jpg",
        },
        {
            name: "Kevin Durant",
            position: forward._id,
            points: "23,883	",
            rebounds: "6,239",
            assists: "3,681",
            championships: "2 times (2017, 2018)",
            HoFYear: "TBD",
            bioHighlight: "UNSTOPPABLE FORCE. UNLIMITED ABILITY.",
            biography: "One of the league’s most lethal scorers, Kevin Durant is a two-time NBA champion, former Rookie of the Year (2008), a four-time scoring champion (2010-14), an MVP and a two-time Finals MVP. Durant’s four scoring titles ties George Gervin and Allen Iverson for the third-most in NBA history.",
            image: "https://cdn.nba.com/manage/2021/10/kevin_durant5-scaled.jpg",
        },
        {
            name: "Kobe Bryant",
            position: guard._id,
            points: "33,643",
            rebounds: "7,047",
            assists: "6,306",
            championships: "5 times (2000, 2001, 2002, 2009, 2010)",
            HoFYear: "2020",
            bioHighlight: "LEGACY OF UNWAVERED PASSION AND WORK ETHIC.",
            biography: "An iconic player on one of the NBA's best-known franchises, Kobe Bryant amassed a career that stands out. He was league MVP, a two-time Finals MVP, is the Lakers' all-time leading scorer and, for many, is in the discussion of the greatest player of all time in NBA history thanks to his starring role in five different Lakers championship teams of the early 2000s.",
            image: "https://cdn.nba.com/manage/2021/10/kobebryant_4-scaled.jpg",
        },
        {
            name: "Dirk Nowitzki",
            position: forward._id,
            points: "31,560",
            rebounds: "11,489",
            assists: "3,651",
            championships: "1 time (2011)",
            HoFYear: "TBD",
            bioHighlight: "A FADEAWAY MADE FOR THE LIMELIGHT.",
            biography: "The son of elite athletes — father Jörg-Werner represented Germany as an international handball player, while mother Helga played basketball professionally -— Nowitzki turned pro himself at 16 years old with the local club in his hometown of Wurzburg.",
            image: "https://cdn.nba.com/manage/2021/10/dirk_nowitzki1-scaled.jpg",
        },
        {
            name: "Kevin Garnett",
            position: forward._id,
            points: "26,071",
            rebounds: "14,662",
            assists: "5,445",
            championships: "1 time (2008)",
            HoFYear: "2020",
            bioHighlight: "A DRIVE SO STRONG IT INSPIRED OTHERS.",
            biography: "Kevin Garnett is one of three players in NBA history -- Kareem Abdul-Jabbar and Karl Malone are the others -- with at least 20,000 career points, 10,000 career rebounds and 5,000 career assists. He's also one of two players -- Hakeem Olajuwon is the other -- with at least 1,800 career steals and 1,800 career blocks.",
            image: "https://cdn.nba.com/manage/2021/10/kevin_garnett15-scaled.jpg",
        },
        {
            name: "Allen Iverson",
            position: guard._id,
            points: "24,368",
            rebounds: "3,394",
            assists: "5,624",
            championships: "None",
            HoFYear: "2016",
            bioHighlight: "IMPACTED CULTURE WITH STYLE AND SWAG.",
            biography: "Allen Iverson graced the NBA hardwood for 14 seasons as one of the most prolific scorers in the history of the game. He excelled at both the point guard and shooting guard position despite his small stature. At 6-feet tall and 165 pounds, Iverson shredded opposing defenses with his unique talent and captivated fans worldwide with his additional flair.",
            image: "https://cdn.nba.com/manage/2021/10/allen_iverson3-scaled.jpg",
        },
        {
            name: "Shaquille O'Neal",
            position: center._id,
            points: "28,596",
            rebounds: "13,099",
            assists: "3,026",
            championships: "4 times (2000, 2001, 2002, 2006)",
            HoFYear: "2016",
            bioHighlight: "THE ENTERTAINER WITH UNLIMITED TALENT.",
            biography: "Shaquille O’Neal is widely regarded as one of the most dominant players in NBA history. He amassed a number of accolades throughout 19 seasons in the league, including Rookie of the Year and MVP honors. O’Neal won four NBA titles and was named Finals MVP three times.",
            image: "https://cdn.nba.com/manage/2021/10/04ADB8ONealShaquille-scaled.jpg",
        },
        {
            name: "David Robinson",
            position: center._id,
            points: "20,790",
            rebounds: "10,497",
            assists: "2,441",
            championships: "2 times (1999, 2003)",
            HoFYear: "2009",
            bioHighlight: "THE PERSONIFICATION OF POWER AND GRACE.",
            biography: `Before there was Tim Duncan, there was David "The Admiral" Robinson. The legendary San Antonio Spurs center averaged 21.1 points and 10.6 rebounds over his 14-year career, laying the groundwork for the Spurs to become a dynasty. He won two NBA championships, an MVP award and was a 10-time All-NBA selection in his career.",
            image: "https://cdn.nba.com/manage/2021/10/david_robinson1-1-scaled.jpg`,
        },
        {
            name: "Hakeem Olajuwon",
            position: center._id,
            points: "26,946",
            rebounds: "13,748",
            assists: "3,058",
            championships: "2 times (1994, 1995)",
            HoFYear: "2008",
            bioHighlight: "AN ICON DOMINATING BOTH ENDS OF THE COURT.",
            biography: `Hakeem "The Dream" Olajuwon established himself as one of the most dominant and accomplished players of his era. His long list of accolades include an MVP award, two Finals MVP trophies and two Defensive Player of the Year honors.`,
            image: "https://cdn.nba.com/manage/2021/10/hakeem_olajuwon4-scaled.jpg",
        },
        {
            name: "Charles Barkley",
            position: forward._id,
            points: "23,757",
            rebounds: "12,546",
            assists: "4,215",
            championships: "None",
            HoFYear: "2006",
            bioHighlight: "BIG GAME AND EVEN BIGGER PERSONALITY.",
            biography: "Although he was initially thought to be undersized to some at 6-foot-6 to play his position, Charles Barkley became one of the NBA's best power forwards ever. Known for his tenacious rebounding and low-post scoring, Barkley was equally deft at running or finishing a fast break and was known for his solid court vision.",
            image: "https://cdn.nba.com/manage/2021/10/charles_barkley9-scaled.jpg",
        },
        {
            name: "Julius Erving",
            position: forward._id,
            points: "18,364",
            rebounds: "5,601",
            assists: "3,224",
            championships: "1 time (1983)",
            HoFYear: "1993",
            bioHighlight: "VIBRANT AND CREATIVE INNOVATOR OF THE AIR.",
            biography: `Known to many by his nicknames "Dr. J" and "The Doctor," Julius Erving was among the most exciting players in NBA history. He was known for jaw-dropping athleticism manifesting in dunks that were both powerful and graceful. To "posterize" a defender remains basketball slang believed to have originated with Erving's penchant for dunking over opposing players in spectacular fashion.`,
            image: "https://cdn.nba.com/manage/2021/10/julius_erving14-scaled.jpg",
        },
        {
            name: "Bill Walton",
            position: center._id,
            points: "6,215",
            rebounds: "4,923",
            assists: "1,590",
            championships: "2 times (1977,1986)",
            HoFYear: "1993",
            bioHighlight: "THE PLAYER THAT COULD DO IT ALL.",
            biography: "An elite defender, passer, and rebounder, Bill Walton entered the NBA as one of the most highly anticipated talents in league history after a sterling NCAA career at UCLA. Walton scored, passed, intimidated, hustled, and played the role of leader with the best centers of his day.",
            image: "https://cdn.nba.com/manage/2021/10/bill_walton7-scaled.jpg",
        },
        {
            name: "Bob McAdoo",
            position: forward._id,
            points: "18,787",
            rebounds: "8,048",
            assists: "1,951",
            championships: "2 times (1982, 1985)",
            HoFYear: "2000",
            bioHighlight: "HIS OFFENSIVE PROWESS SET THE BAR.",
            biography: "Few players in NBA history had as bright of a start to their careers as Bob McAdoo did. By the time he was in his third season, McAdoo had been named Rookie of the Year, MVP and had two scoring titles as a standout player for the Buffalo Braves (now known as the LA Clippers).",
            image: "https://cdn.nba.com/manage/2021/10/bob_mcadoo6-scaled.jpg",
        },
        {
            name: "Dave Cowens",
            position: center._id,
            points: "13,516",
            rebounds: "10,444",
            assists: "2,910",
            championships: "2 times (1974, 1976)",
            HoFYear: "1991",
            bioHighlight: "TENACIOUS BIG MAN WITH HUSTLE AND HEART.",
            biography: "Dave Cowens was a double-double machine for the Boston Celtics, who won NBA titles with him leading the way in 1974 and '76. A star in his own right and a former MVP, Cowens was known for his consistency, versatility and energy as one of the most solid centers of his era.",
            image: "https://cdn.nba.com/manage/2021/10/dave_cowens1-1-scaled.jpg",
        },
        {
            name: "Willis Reed	",
            position: center._id,
            points: "12,183",
            rebounds: "8,414",
            assists: "1,186",
            championships: "2 times (1970,1973)",
            HoFYear: "1982",
            bioHighlight: "STRUCK GOLD AS A RESILIENT CENTER.",
            biography: "For a decade, Willis Reed brought physicality and force to the Madison Square Garden floor, and was a key cog on the New York Knicks' championship teams of the 1970s. Reed averaged double-figure scoring in each of his 10 seasons and at least 11.6 rebounds per game in seven of them.",
            image: "https://cdn.nba.com/manage/2021/10/Willis-Reed-scaled.jpg",
        },
        {
            name: "Wes Unseld",
            position: center._id,
            points: "12,183",
            rebounds: "8,414",
            assists: "1,186",
            championships: "1 (1978)",
            HoFYear: "1988",
            bioHighlight: "DOMINATED THE GLASS WITH DEFENSIVE SAVVY.",
            biography: "A physical, gritty big man, Wes Unseld was known for his toughness, outlet passes and relentless rebounding. Perhaps the most beloved player in Washington's franchise history, Unseld steered the team to its lone NBA championship and four NBA Finals appearances.",
            image: "https://cdn.nba.com/manage/2021/10/80RIPS-5Unseld-scaled.jpg",
        },
        {
            name: "Oscar Robertson",
            position: guard._id,
            points: "26,710",
            rebounds: "7,804",
            assists: "9,887",
            championships: "1 (1971)",
            HoFYear: "1980",
            bioHighlight: "THE SKILLFUL PARADIGM OF VERSATILITY.",
            biography: "At 6-foot-5 and 210 pounds, Robertson was the NBA's first big guard and the first player in league history to average a triple-double for a season. An All-NBA and All-Star performer throughout his career, Robertson was an MVP and the leader of the Milwaukee Bucks' first championship team in 1971.",
            image: "https://cdn.nba.com/manage/2021/10/1464826_10-scaled.jpg",
        },
        {
            name: "Bob Cousy",
            position: guard._id,
            points: "16,960",
            rebounds: "4,708",
            assists: "2,791",
            championships: "6 (1957, 1959, 1960, 1961, 1962, 1963)",
            HoFYear: "1971",
            bioHighlight: "PLAYMAKER WITH A REVOLUTIONARY STYLE.",
            biography: "Perhaps the first showman guard in NBA history, Bob Cousy set the tone for point guard play in the league for decades to come.",
            image: "https://cdn.nba.com/manage/2021/10/bob_cousy9-scaled.jpg",
        },
        {
            name: "James Worthy",
            position: forward._id,
            points: "16,320",
            rebounds: "4,708",
            assists: "2,791",
            championships: "3 (1985, 1987, 1988)",
            HoFYear: "2003",
            bioHighlight: "WHEN THE PRESSURE IS ON, SO WAS HIS GAME.",
            biography: "James Worthy brought athletic skills and clutch performances to the Los Angeles Lakers during they heyday of the 1980s as a versatile small forward. He is a legendary player in franchise lore and was one of the best players at his position in his era.",
            image: "https://cdn.nba.com/manage/2021/10/james_worthy6-scaled.jpg",
        },
        {
            name: "Dominique Wilkins",
            position: forward._id,
            points: "26,668",
            rebounds: "7,169",
            assists: "2,677",
            championships: "None",
            HoFYear: "2006",
            bioHighlight: "A DUNKING MARVEL FLYING HIGH.",
            biography: "One of the most exciting players of his generation, Dominique Wilkins was nicknamed “The Human Highlight Film” for his tendency to create made-for-TV moments with his jaw-dropping dunks and finishes at the rim. In the 1980s and '90s, he elevated the Atlanta Hawks to a playoff team and contender in the Eastern Conference.",
            image: "https://cdn.nba.com/manage/2020/10/dominique-wilkins-iso-scaled-e1603381535880.jpg",
        },
        {
            name: "Lenny Wilkens",
            position: guard._id,
            points: "17,772",
            rebounds: "5,030",
            assists: "7,211",
            championships: "None",
            HoFYear: "1989",
            bioHighlight: "GREATNESS SPANNING BEYOND COURT.",
            biography: "Lenny Wilkens was one of the best floor generals ever, immediately starting as rookie for a Hawks team that made it all the way to the 1961 Finals.",
            image: "https://cdn.nba.com/manage/2021/10/lennywilkens_15-scaled.jpg",
        },
        {
            name: "Jerry West",
            position: guard._id,
            points: "25,192",
            rebounds: "5,366",
            assists: "6,238",
            championships: "1 (1972)",
            HoFYear: "1980",
            bioHighlight: "IF “CAME IN CLUTCH” WAS A PERSON.",
            biography: "Along with Oscar Robertson, Jerry West was one of the leading guards of his era. He was a dominant two-way force who helped modernize the position with an elite jumper, deft playmaking and outstanding defense. He is the only player from a losing team to be named Finals MVP and was one of the best scorers in NBA and Los Angeles Lakers history.",
            image: "https://cdn.nba.com/manage/2021/10/jerry_west10-scaled.jpg",
        },
        {
            name: "Dwyane Wade",
            position: guard._id,
            points: "23,165",
            rebounds: "4,933",
            assists: "5,701",
            championships: "3 (2006, 2012, 2013)",
            HoFYear: "TBD",
            bioHighlight: "LIMITLESS CHAMPION BRINGING THE HEAT.",
            biography: "One of the most electric players of his generation and a former Finals MVP, Dwyane Wade is one of the best-known, most successful and most iconic players in Miami Heat history. A strong finisher at the basket and a clutch playoff performer, Wade is Miami's all-time leader in eight different offensive categories.",
            image: "https://cdn.nba.com/manage/2021/10/dwyane_wade3-scaled.jpg",
        },
        {
            name: "Nate Thurmond",
            position: center._id,
            points: "14,437",
            rebounds: "14,464",
            assists: "2,575",
            championships: "None",
            HoFYear: "1985",
            bioHighlight: "SUPERIOR SHOT BLOCKER DOMINATED DEFENSE.",
            biography: "Nate Thurmond was an elite big man in a time when Wilt Chamberlain and Bill Russell roamed the NBA earth, delivering solid offense and defense as well as elite rebounding. The first player in NBA history to log a quadruple-double, Thurmond logged at least 15 rpg in eight of his first 12 seasons.",
            image: "https://cdn.nba.com/manage/2021/10/ThurmondN91NBA867.jpg",
        },
        {
            name: "Isiah Thomas",
            position: guard._id,
            points: "18,822",
            rebounds: "3,478",
            assists: "9,061",
            championships: "2 (1989, 1990)",
            HoFYear: "2000",
            bioHighlight: "THE SCRAPPY, SMART, BAD BOY PLAYMAKER.",
            biography: `Despite standing just 6-foot-1, Isiah Thomas made a large impression on the NBA in the 1980s. He took the Pistons from an also-ran team to two NBA championships and became one of the greatest "small men" in NBA history while becoming a legendary and beloved figure in Detroit sports history.`,
            image: "https://cdn.nba.com/manage/2021/10/isiah_thomas2-scaled.jpg",
        },
        {
            name: "John Stockton",
            position: guard._id,
            points: "19,711",
            rebounds: "4,051",
            assists: "15,806",
            championships: "None",
            HoFYear: "2009",
            bioHighlight: "LEADER ON THE FLOOR COMPETITORS DREADED.",
            biography: "John Stockton was perhaps the NBA's most complete floor general, finishing his 19-year career as the NBA's all-time leader in assists (15,806) and steals (3,265) while shooting 51.5% in his career despite being a mere 6-foot-1 and 170 pounds.",
            image: "https://cdn.nba.com/manage/2021/10/john_stockton15-scaled.jpg",
        },
        {
            name: "Bill Sharman",
            position: guard._id,
            points: "12,665",
            rebounds: "2,779",
            assists: "2,101",
            championships: "4 (1957, 1959, 1960, 1961)",
            HoFYear: "1976",
            bioHighlight: "A COACH AS TRIUMPHANT AS HIS SHOT.",
            biography: "Few in NBA history enjoyed the kind of success Bill Sharman did as both a player and coach. He was one of the top shooters and an All-NBA performer in his playing days with the Boston Celtics. As a professional coach, he won titles in three different leagues and oversaw the longest regular-season win streak in NBA history, too.",
            image: "https://cdn.nba.com/manage/2021/10/bill_sharman6-scaled.jpg",
        },
        {
            name: "Dolph Schayes",
            position: forward._id,
            points: "18,438",
            rebounds: "11,256",
            assists: "3,072",
            championships: "1 (1955)",
            HoFYear: "1973",
            bioHighlight: "A SHOOTING REVOLUTIONARY.",
            biography: "Dolph Schayes’ second season as a pro (1949-50) marked the NBA’s first season after merging the Basketball Association of America with the National Basketball League. The power forward led the Syracuse Nationals to the playoffs on 15 occasions, winning his lone championship in 1955 over the Fort Wayne Pistons.",
            image: "https://cdn.nba.com/manage/2021/10/dolph_schayes5-scaled.jpg",
        },
        {
            name: "Dennis Rodman",
            position: forward._id,
            points: "6,683",
            rebounds: "11,954",
            assists: "1,600",
            championships: "5 (1989, 1990, 1996, 1997, 1998)",
            HoFYear: "2011",
            bioHighlight: "AHEAD-OF-HIS-TIME STYLE AND SKILL.",
            biography: "A rebounding expert if ever there was one in NBA history, Dennis Rodman stands among the all-time greats in that area of the game. A two-time Defensive Player of the Year, Rodman was a part of five championship teams and crucial to the dynasties of the Detroit Pistons and Chicago Bulls.",
            image: "https://cdn.nba.com/manage/2021/10/dennis_rodman2-scaled.jpg",
        },
        {
            name: "Scottie Pippen",
            position: forward._id,
            points: "18,940",
            rebounds: "7,494",
            assists: "6,135",
            championships: "6 (1991, 1992, 1993, 1996, 1997, 1998)",
            HoFYear: "2010",
            bioHighlight: "AN UNDENIABLE PROTOTYPE FOR TWO-WAY PLAY.",
            biography: "The Chicago Bulls landed one of the greatest small forwards of all time when they acquired Scottie Pippen from the Seattle SuperSonics just weeks after the 1987 NBA Draft. Pippen would go on to become one of the most decorated and versatile players in the history of the game.",
            image: "https://cdn.nba.com/manage/2021/10/S0611_Blls_v_Jzz_AH001-scaled.jpg",
        },
        {
            name: "Paul Pierce",
            position: forward._id,
            points: "26,397",
            rebounds: "7,527",
            assists: "4,708",
            championships: "1 time (2008)",
            HoFYear: "2021",
            bioHighlight: "A COMPLETE PLAYER, HE CAN DO IT ALL.",
            biography: "Paul Pierce set out to prove his doubters wrong almost immediately in his career and more than accomplished his goal. The star of the Boston Celtics in the 2000s, Pierce led the team to an NBA title in 2008 and another Finals berth in 2010, all while etching his name in Celtics lore with both statistical feats and memorable moments.",
            image: "https://cdn.nba.com/manage/2021/10/570267_10-scaled.jpg",
        },
        {
            name: "Gary Payton",
            position: guard._id,
            points: "21,813",
            rebounds: "5,269",
            assists: "8,966",
            championships: "1 time (2006)",
            HoFYear: "2013",
            bioHighlight: "A WHOLE NEW LEVEL OF DEFENSIVE DOMINATION.",
            biography: "Widely considered one of the greatest defenders in NBA history, the native of Oakland, Calif., and product of Oregon State is the only point guard to win Defensive Player of the Year in the award’s 39-year history. He was an All-Defensive Team selection nine times to go with his nine All-NBA and nine All-Star honors.",
            image: "https://cdn.nba.com/manage/2021/10/garypayton_2-scaled.jpg",
        },
        {
            name: "Chris Paul",
            position: guard._id,
            points: "19,978",
            rebounds: "4,923",
            assists: "10,275",
            championships: "None",
            HoFYear: "TBD",
            bioHighlight: "A LEADER WITH SUPERB PLAYMAKING VISION.",
            biography: "One of the most talented passers to ever play the game, Chris Paul continues to stand out as a floor general in NBA lore. He owns four assist crowns and has averaged eight assists or better in all but three of his seasons in the league.",
            image: "https://cdn.nba.com/manage/2021/10/chris_paul13-scaled.jpg",
        },
        {
            name: "Robert Parish",
            position: center._id,
            points: "23,334",
            rebounds: "14,715",
            assists: "2,180",
            championships: "4 times (1981, 1984, 1986, 1997)",
            HoFYear: "2003",
            bioHighlight: "THE JUMPER THAT KISSED THE BANNERS.",
            biography: `Known for his mid-range jumper and defensive presence for the Celtics in the 1980s, Robert Parish was a part of Boston's Hall of Fame "Big Three" comprised of he, Larry Bird and Kevin McHale. The nine-time All-Star finished among the top 10 in the league in field goal percentage for six consecutive seasons and topped 10 rebounds per game in eight seasons.`,
            image: "https://cdn.nba.com/manage/2021/10/Parish86SCR55-scaled.jpg",
        },
        {
            name: "Earl Monroe",
            position: guard._id,
            points: "17,454",
            rebounds: "2,796",
            assists: "3,594",
            championships: "1 time (1973)",
            HoFYear: "1990",
            bioHighlight: "BRILLIANT GUARD THAT KNEW HOW TO PUT ON A SHOW.",
            biography: `Earl "The Pearl" Monroe was one of the most exciting and innovative players to ever grace an NBA court. He posted a career average of 18.8 points per game across 13 seasons with the Baltimore Bullets (now Washington Wizards) and the New York Knicks.`,
            image: "https://cdn.nba.com/manage/2021/10/earl_monroe8-scaled.jpg",
        },
        {
            name: "Reggie Miller",
            position: guard._id,
            points: "26,279",
            rebounds: "4,182",
            assists: "4,141",
            championships: "None",
            HoFYear: "2012",
            bioHighlight: "MADE HIS MARK WITH A PARAMOUNT 3-POINTER.",
            biography: `Reggie Miller is one of the premier 3-point shooters in NBA history and owned most of the major records from that distance upon his retirement in 2005. He was adept at coming off screens from various spots on the floor and was known as "Miller Time" for his heroic play down the stretch of games.`,
            image: "https://cdn.nba.com/manage/2021/10/52822037_10-scaled.jpg",
        },
        {
            name: "George Mikan",
            position: center._id,
            points: "10,156",
            rebounds: "4,167",
            assists: "1,245",
            championships: "5 (1949, 1950, 1952, 1953, 1954)",
            HoFYear: "1959",
            bioHighlight: "PIONEERED THE NEXT ERA OF GREATNESS.",
            biography: "One of the most dominant figures in the early days of basketball as well as the NBA, George Mikan prompted the “Mikan rule” (which widened the lane from 6 to 12 feet), the introduction of the 24-second shot clock to keep teams from stalling to minimize his impact on games and the goaltending rule.",
            image: "https://cdn.nba.com/manage/2021/10/Mikan-Color-scaled.jpg",
        },
        {
            name: "Kevin McHale",
            position: forward._id,
            points: "17,335",
            rebounds: "7,122",
            assists: "1,670",
            championships: "3 times (1981, 1984, 1986)",
            HoFYear: "1999",
            bioHighlight: "A MASTER OF FOOTWORK AND POST-MOVES.",
            biography: "Kevin McHale won three NBA championships alongside Hall of Famers Larry Bird, Dennis Johnson and Robert Parish during his 13-season career with the Celtics.",
            image: "https://cdn.nba.com/manage/2021/10/kevin_mchale10-scaled.jpg",
        },
        {
            name: "Pete Maravich",
            position: guard._id,
            points: "15,948",
            rebounds: "2,747",
            assists: "3,563",
            championships: "None",
            HoFYear: "1987",
            bioHighlight: "HIS CREATIVE GAME HAD A STYLE OF ITS OWN",
            biography: "A flashy scorer with incredible handle and unprecedented range, well before all three became fashionable elements of the NBA game, Pete Maravich's 10-season NBA career featured a flurry of all-angles basket-making (24.2 ppg) and mind-bending passes (5.4 apg).",
            image: "https://cdn.nba.com/manage/2021/10/S0101WI001_Maravich_drives-scaled.jpg",
        },
        {
            name: "Jerry Lucas",
            position: forward._id,
            points: "14,053",
            rebounds: "12,942",
            assists: "2,732",
            championships: "1 time (1973)",
            HoFYear: "1980",
            bioHighlight: "THE PLAYER WITH THE PLAN.",
            biography: `Jerry Lucas was a winner at every level and one of the best rebounding forwards the game has ever seen. His career average of 15.6 rebounds per game ranks fourth in NBA history and he was a key player in the New York Knicks' championship team of 1973.`,
            image: "https://cdn.nba.com/manage/2021/10/jerry_lucas3-scaled.jpg",
        },
                                                                                
                                                                                
    ]


    await Player.insertMany(players)
    console.log('Players create')
}

const run = async () => {
    await main()
    db.close()
}

run()




// {
//     name: "",
//     position: "",
//     points: "",
//     rebounds: "",
//     assists: "",
//     championships: "",
//     HoFYear: "",
//     bioHighlight: "",
//     biography: "",
//     image: "",
// },




//Postion description credit:
//https://jr.nba.com/basketball-positions/

//Players stats, bio highlights/biography:
//https://www.nba.com/75/team